### PR TITLE
Proxy support and organized codes.txt

### PR DESCRIPTION
**Pull request by NotClavilux**
- Organized the codes.txt for easier reading (added space after every link)
- Proxy support, faster generation
- Overall improved code

### CODE REVIEW

**Comment by NotClavilux** [comment]
Forgot to mention but HTTP proxies are supported only 💯

**Comment by OddDevelopment** [comment]
Hey so I was testing by replacing the URL with my own site and looking at the logs and the proxies seem to not be the IP sending the requests but instead the real IP of the machine.

**Comment by NotClavilux** [comment]
Huh, that's weird, i'm gonna check it out

**Comment by NotClavilux** [comment]
Yeah f*ck proxies, i'm gonna close this pull request and just add other optimizations etc without proxies frfr

**Pull request closed without merging**
